# fly.toml app configuration file generated for deploy-app-twilight-mountain-1862 on 2025-07-06T16:52:59+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deploy-app-twilight-mountain-1862'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = './bin/rails db:migrate'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'